<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '11',
    'typeid' => '0',
    'title' => '快步赞助四大园年例衣服',
    'style' => '',
    'thumb' => 'http://www.kb.com/uploadfile/2019/0318/20190318115530595.jpg',
    'keywords' => '快步赞助衣服',
    'description' => 'NSdkjakemadf adf吗，大是大非发生的发生的发丰盛的人哦，满腹经纶卡迪夫吗，',
    'posids' => '1',
    'url' => 'http://www.kb.com/index.php?m=content&c=index&a=show&catid=11&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1552872169',
    'updatetime' => '1552872536',
    'hitsid' => 'c-1-1',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '11',
    'typeid' => '0',
    'title' => ' 【装修风水】雅致主义装修风格，追求品味与和谐',
    'style' => '',
    'thumb' => 'http://www.kb.com/uploadfile/2019/0318/20190318115504866.jpg',
    'keywords' => '',
    'description' => '【雅致主义装修风格特点】雅致主义是带有极强文化品味的装饰风格，它打破了现代主义的造型形式和装饰手法，注重线型的搭配和颜色的协调，反   ',
    'posids' => '1',
    'url' => 'http://www.kb.com/index.php?m=content&c=index&a=show&catid=11&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1552872984',
    'updatetime' => '1552873840',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '11',
    'typeid' => '0',
    'title' => '品鉴设计，感悟匠心 | 百创整装代表团赴日本考察交流！',
    'style' => '',
    'thumb' => 'http://www.kb.com/uploadfile/2019/0318/20190318033139209.png',
    'keywords' => '快步赞助衣服',
    'description' => '近日，百创整装代表团受邀前往日本知名装修企业与家装博览会进行考察与交流，旨在吸收借鉴日本舒适家居人性化设计，引进先进创新、充满匠心   ',
    'posids' => '0',
    'url' => 'http://www.kb.com/index.php?m=content&c=index&a=show&catid=11&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1552894135',
    'updatetime' => '1552894256',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>